FROM pytorch/pytorch

# Copy
COPY . /kcg-ml-elm
WORKDIR /kcg-ml-elm

# mirror
RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

RUN pip3 install -r ./requirements-docker.txt

WORKDIR /kcg-ml-elm
CMD ["python3", "run-all-notebooks.py"]