FROM pytorch/pytorch

# Copy
COPY . /kcg-ml-elm
WORKDIR /kcg-ml-elm

# local pip cache
RUN pip3 config set global.index-url http://192.168.3.2:5010/index/
RUN pip3 config set global.trusted-host 192.168.3.2

RUN pip3 install -r ./requirements-docker.txt

WORKDIR /kcg-ml-elm
CMD ["python3", "run-all-notebooks.py"]
